// <auto-generated />
using System;
using FlowForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowForgeDbContext))]
    [Migration("20261009172619_PersistenciaInicial")]
    partial class PersistenciaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.TechnicalUserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("ck_users_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowConnectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_node_id");

                    b.Property<string>("SourcePort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_port");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_node_id");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_connections");

                    b.HasIndex("WorkflowVersionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_connections_version_id_ordinal");

                    b.HasIndex("WorkflowVersionId", "TargetNodeId")
                        .HasDatabaseName("ix_workflow_connections_version_id_target_node_id");

                    b.HasIndex("WorkflowVersionId", "SourceNodeId", "SourcePort")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_connections_version_id_source_node_id_source_port");

                    b.ToTable("workflow_connections", "public", t =>
                        {
                            t.HasCheckConstraint("ck_workflow_connections_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_workflow_connections_ordinal", "ordinal >= 0 AND length(btrim(source_port)) > 0");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", b =>
                {
                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("WorkflowVersionId", "NodeId")
                        .HasName("pk_workflow_nodes");

                    b.HasIndex("WorkflowVersionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_nodes_version_id_ordinal");

                    b.HasIndex("WorkflowVersionId", "WorkflowId", "OwnerUserId")
                        .HasDatabaseName("ix_workflow_nodes_version_id_workflow_id_owner_user_id");

                    b.ToTable("workflow_nodes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_workflow_nodes_config", "jsonb_typeof(configuration) = 'object' AND configuration ? 'schemaVersion' AND configuration->>'schemaVersion' = '1'");

                            t.HasCheckConstraint("ck_workflow_nodes_credential", "credential_id IS NULL OR (type = 2 AND credential_id <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("ck_workflow_nodes_id", "node_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_workflow_nodes_position", "position_x > '-Infinity'::float8 AND position_x < 'Infinity'::float8 AND position_y > '-Infinity'::float8 AND position_y < 'Infinity'::float8");

                            t.HasCheckConstraint("ck_workflow_nodes_type", "type BETWEEN 1 AND 6 AND ordinal >= 0");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentPublishedVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_published_version_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasAlternateKey("Id", "OwnerUserId")
                        .HasName("ak_workflows_id_owner_user_id");

                    b.HasIndex("CurrentPublishedVersionId", "Id", "OwnerUserId")
                        .HasDatabaseName("ix_workflows_current_published_version_id_id_owner_user_id");

                    b.HasIndex("OwnerUserId", "UpdatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_workflows_owner_user_id_updated_at_id");

                    b.ToTable("workflows", "public", t =>
                        {
                            t.HasCheckConstraint("ck_workflows_dates", "updated_at >= created_at AND (archived_at IS NULL OR archived_at = updated_at)");

                            t.HasCheckConstraint("ck_workflows_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_workflows_name", "length(btrim(name)) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("ck_workflows_revision", "revision >= 0");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_versions");

                    b.HasAlternateKey("Id", "WorkflowId", "OwnerUserId")
                        .HasName("ak_workflow_versions_id_workflow_id_owner_user_id");

                    b.HasIndex("WorkflowId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_versions_workflow_id")
                        .HasFilter("status = 1");

                    b.HasIndex("WorkflowId", "OwnerUserId")
                        .HasDatabaseName("ix_workflow_versions_workflow_id_owner_user_id");

                    b.HasIndex("WorkflowId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_versions_workflow_id_version_number");

                    b.ToTable("workflow_versions", "public", t =>
                        {
                            t.HasCheckConstraint("ck_workflow_versions_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_workflow_versions_revision", "revision >= 0 AND version_number > 0");

                            t.HasCheckConstraint("ck_workflow_versions_status", "(status = 1 AND published_at IS NULL) OR (status = 2 AND published_at IS NOT NULL AND published_at >= created_at)");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowConnectionRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId", "SourceNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_connections_workflow_version_id_source_node_id");

                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId", "TargetNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_connections_workflow_version_id_target_node_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId", "WorkflowId", "OwnerUserId")
                        .HasPrincipalKey("Id", "WorkflowId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_nodes_workflow_version_id_workflow_id_owner_user_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.TechnicalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_owner_user_id");

                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("CurrentPublishedVersionId", "Id", "OwnerUserId")
                        .HasPrincipalKey("Id", "WorkflowId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_workflows_current_published_version_id_id_owner_user_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowVersionRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_versions_workflow_id_owner_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
