// <auto-generated />
using System;
using FlowForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowForgeDbContext))]
    partial class FlowForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.ExecutionLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EventCode")
                        .HasColumnType("integer")
                        .HasColumnName("event_code");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<int>("MessageByteLength")
                        .HasColumnType("integer")
                        .HasColumnName("message_byte_length");

                    b.Property<byte[]>("MessageProtected")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("message_protected");

                    b.Property<Guid>("NodeExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_execution_id");

                    b.HasKey("Id")
                        .HasName("pk_execution_logs");

                    b.HasIndex("NodeExecutionId")
                        .IsUnique()
                        .HasDatabaseName("ix_execution_logs_node_execution_id");

                    b.HasIndex("NodeExecutionId", "ExecutionId")
                        .HasDatabaseName("ix_execution_logs_node_execution_id_execution_id");

                    b.HasIndex("ExecutionId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_execution_logs_execution_id_created_at_id");

                    b.ToTable("execution_logs", "public", t =>
                        {
                            t.HasCheckConstraint("ck_execution_log_content", "event_code = 1 AND message_byte_length BETWEEN 1 AND 8000 AND octet_length(message_protected) BETWEEN 1 AND 16384");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.InboxMessageRecord", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ClaimAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("claim_attempts");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_token");

                    b.Property<DateTimeOffset?>("ClaimUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_until");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("MessageId")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ExecutionId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_execution_id");

                    b.HasIndex("MessageId", "ExecutionId")
                        .HasDatabaseName("ix_inbox_messages_message_id_execution_id");

                    b.ToTable("inbox_messages", "public", t =>
                        {
                            t.HasCheckConstraint("ck_inbox_state", "claim_attempts > 0 AND ((completed_at IS NULL AND claim_token IS NOT NULL AND claim_until IS NOT NULL) OR (completed_at IS NOT NULL AND completed_at >= received_at AND claim_token IS NULL AND claim_until IS NULL))");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.NodeExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("integer")
                        .HasColumnName("error_code");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("InputSummary")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_summary");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("OutputSummary")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_summary");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id")
                        .HasName("pk_node_executions");

                    b.HasAlternateKey("Id", "ExecutionId")
                        .HasName("ak_node_executions_id_execution_id");

                    b.HasIndex("ExecutionId", "NodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_node_executions_execution_id_node_id");

                    b.HasIndex("ExecutionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_node_executions_execution_id_ordinal");

                    b.HasIndex("ExecutionId", "WorkflowVersionId")
                        .HasDatabaseName("ix_node_executions_execution_id_version_id");

                    b.HasIndex("WorkflowVersionId", "NodeId")
                        .HasDatabaseName("ix_node_executions_version_id_node_id");

                    b.ToTable("node_executions", "public", t =>
                        {
                            t.HasCheckConstraint("ck_node_execution_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND ordinal >= 0");

                            t.HasCheckConstraint("ck_node_execution_state", "(status = 1 AND attempt_count = 0 AND started_at IS NULL AND finished_at IS NULL AND input_summary IS NULL AND output_summary IS NULL AND error_code IS NULL) OR (status = 2 AND attempt_count > 0 AND started_at IS NOT NULL AND finished_at IS NULL AND input_summary IS NOT NULL AND output_summary IS NULL AND error_code IS NULL) OR (status = 3 AND attempt_count > 0 AND started_at IS NOT NULL AND finished_at IS NOT NULL AND finished_at >= started_at AND input_summary IS NOT NULL AND output_summary IS NOT NULL AND error_code IS NULL) OR (status = 4 AND attempt_count > 0 AND started_at IS NOT NULL AND finished_at IS NOT NULL AND finished_at >= started_at AND input_summary IS NOT NULL AND output_summary IS NULL AND error_code IS NOT NULL AND error_code BETWEEN 1 AND 7) OR (status = 6 AND attempt_count = 0 AND started_at IS NULL AND finished_at IS NOT NULL AND input_summary IS NULL AND output_summary IS NULL AND error_code IS NULL) OR (status = 7 AND attempt_count > 0 AND started_at IS NOT NULL AND finished_at IS NOT NULL AND finished_at >= started_at AND input_summary IS NOT NULL AND output_summary IS NULL AND error_code IS NULL)");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.OutboxMessageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_token");

                    b.Property<DateTimeOffset?>("ClaimUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_until");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer")
                        .HasColumnName("contract_version");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("publish_attempts");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasAlternateKey("Id", "ExecutionId")
                        .HasName("ak_outbox_messages_id_execution_id");

                    b.HasIndex("ExecutionId")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_messages_execution_id");

                    b.HasIndex("AvailableAt", "Id")
                        .HasDatabaseName("ix_outbox_messages_available_at_id")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_messages", "public", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_contract", "contract_version = 1 AND publish_attempts >= 0");

                            t.HasCheckConstraint("ck_outbox_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND correlation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_outbox_lease", "(claim_token IS NULL) = (claim_until IS NULL) AND (published_at IS NULL OR (claim_token IS NULL AND published_at >= created_at))");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.TechnicalUserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("ck_users_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WebhookEndpointRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("secret_hash");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_webhook_endpoints");

                    b.HasAlternateKey("Id", "OwnerUserId")
                        .HasName("ak_webhook_endpoints_id_owner_user_id");

                    b.HasAlternateKey("Id", "WorkflowId", "OwnerUserId")
                        .HasName("ak_webhook_endpoints_id_workflow_id_owner_user_id");

                    b.HasIndex("WorkflowId")
                        .IsUnique()
                        .HasDatabaseName("ix_webhook_endpoints_workflow_id");

                    b.HasIndex("WorkflowId", "OwnerUserId")
                        .HasDatabaseName("ix_webhook_endpoints_workflow_id_owner_user_id");

                    b.ToTable("webhook_endpoints", "public", t =>
                        {
                            t.HasCheckConstraint("ck_webhook_endpoint", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND octet_length(secret_hash) = 32 AND (rotated_at IS NULL OR rotated_at >= created_at)");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WebhookIdempotencyRecord", b =>
                {
                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("KeyDigest")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_digest");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("RequestDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_digest");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("EndpointId", "KeyDigest")
                        .HasName("pk_webhook_idempotency");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_webhook_idempotency_expires_at");

                    b.HasIndex("EndpointId", "WorkflowId", "OwnerUserId")
                        .HasDatabaseName("ix_webhook_idempotency_endpoint_id_workflow_id_owner_user_id");

                    b.HasIndex("ExecutionId", "WorkflowId", "OwnerUserId")
                        .HasDatabaseName("ix_webhook_idempotency_execution_id_workflow_id_owner_user_id");

                    b.ToTable("webhook_idempotency", "public", t =>
                        {
                            t.HasCheckConstraint("ck_webhook_digests", "key_digest ~ '^[0-9A-F]{64}$' AND request_digest ~ '^[0-9A-F]{64}$'");

                            t.HasCheckConstraint("ck_webhook_retention", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowConnectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_node_id");

                    b.Property<string>("SourcePort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_port");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_node_id");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_connections");

                    b.HasIndex("WorkflowVersionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_connections_version_id_ordinal");

                    b.HasIndex("WorkflowVersionId", "TargetNodeId")
                        .HasDatabaseName("ix_workflow_connections_version_id_target_node_id");

                    b.HasIndex("WorkflowVersionId", "SourceNodeId", "SourcePort")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_connections_version_id_source_node_id_source_port");

                    b.ToTable("workflow_connections", "public", t =>
                        {
                            t.HasCheckConstraint("ck_workflow_connections_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_workflow_connections_ordinal", "ordinal >= 0 AND length(btrim(source_port)) > 0");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancel_requested_at");

                    b.Property<int>("CheckpointRevision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("checkpoint_revision");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ErrorCode")
                        .HasColumnType("integer")
                        .HasColumnName("error_code");

                    b.Property<byte[]>("ExecutionContextProtected")
                        .HasColumnType("bytea")
                        .HasColumnName("execution_context_protected");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("NextNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("next_node_id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<byte[]>("TriggerInputProtected")
                        .HasColumnType("bytea")
                        .HasColumnName("trigger_input_protected");

                    b.Property<Guid?>("WebhookEndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("webhook_endpoint_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_executions");

                    b.HasAlternateKey("Id", "WorkflowVersionId")
                        .HasName("ak_workflow_executions_id_workflow_version_id");

                    b.HasAlternateKey("Id", "WorkflowId", "OwnerUserId")
                        .HasName("ak_workflow_executions_id_workflow_id_owner_user_id");

                    b.HasIndex("WorkflowVersionId", "NextNodeId")
                        .HasDatabaseName("ix_workflow_executions_version_id_next_node_id");

                    b.HasIndex("OwnerUserId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_workflow_executions_owner_user_id_created_at_id");

                    b.HasIndex("WebhookEndpointId", "WorkflowId", "OwnerUserId")
                        .HasDatabaseName("ix_workflow_executions_hook_id_workflow_id_owner_user_id");

                    b.HasIndex("WorkflowVersionId", "WorkflowId", "OwnerUserId")
                        .HasDatabaseName("ix_workflow_executions_version_id_workflow_id_owner_user_id");

                    b.ToTable("workflow_executions", "public", t =>
                        {
                            t.HasCheckConstraint("ck_execution_checkpoint", "checkpoint_revision >= 0 AND (execution_context_protected IS NULL OR octet_length(execution_context_protected) BETWEEN 1 AND 131072) AND (cancel_requested_at IS NULL OR cancel_requested_at >= created_at) AND (status IN (1, 2) OR next_node_id IS NULL)");

                            t.HasCheckConstraint("ck_execution_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid AND correlation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_execution_state", "(status = 1 AND started_at IS NULL AND finished_at IS NULL AND error_code IS NULL) OR (status = 2 AND started_at IS NOT NULL AND started_at >= created_at AND finished_at IS NULL AND error_code IS NULL) OR (status = 4 AND started_at IS NOT NULL AND started_at >= created_at AND finished_at IS NOT NULL AND finished_at >= started_at AND error_code IS NOT NULL AND error_code BETWEEN 1 AND 7) OR (status = 3 AND started_at IS NOT NULL AND started_at >= created_at AND finished_at IS NOT NULL AND finished_at >= started_at AND error_code IS NULL) OR (status = 5 AND cancel_requested_at IS NOT NULL AND finished_at IS NOT NULL AND finished_at >= cancel_requested_at AND finished_at >= COALESCE(started_at, created_at) AND (started_at IS NULL OR started_at >= created_at) AND error_code IS NULL)");

                            t.HasCheckConstraint("ck_execution_trigger_input", "(webhook_endpoint_id IS NULL) = (trigger_input_protected IS NULL) AND (trigger_input_protected IS NULL OR octet_length(trigger_input_protected) BETWEEN 1 AND 131072)");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", b =>
                {
                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("WorkflowVersionId", "NodeId")
                        .HasName("pk_workflow_nodes");

                    b.HasIndex("WorkflowVersionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_nodes_version_id_ordinal");

                    b.HasIndex("WorkflowVersionId", "WorkflowId", "OwnerUserId")
                        .HasDatabaseName("ix_workflow_nodes_version_id_workflow_id_owner_user_id");

                    b.ToTable("workflow_nodes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_workflow_nodes_config", "jsonb_typeof(configuration) = 'object' AND configuration ? 'schemaVersion' AND configuration->>'schemaVersion' = '1'");

                            t.HasCheckConstraint("ck_workflow_nodes_credential", "credential_id IS NULL OR (type = 2 AND credential_id <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("ck_workflow_nodes_id", "node_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_workflow_nodes_position", "position_x > '-Infinity'::float8 AND position_x < 'Infinity'::float8 AND position_y > '-Infinity'::float8 AND position_y < 'Infinity'::float8");

                            t.HasCheckConstraint("ck_workflow_nodes_type", "type BETWEEN 1 AND 6 AND ordinal >= 0");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentPublishedVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_published_version_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasAlternateKey("Id", "OwnerUserId")
                        .HasName("ak_workflows_id_owner_user_id");

                    b.HasIndex("CurrentPublishedVersionId", "Id", "OwnerUserId")
                        .HasDatabaseName("ix_workflows_current_published_version_id_id_owner_user_id");

                    b.HasIndex("OwnerUserId", "UpdatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_workflows_owner_user_id_updated_at_id");

                    b.ToTable("workflows", "public", t =>
                        {
                            t.HasCheckConstraint("ck_workflows_dates", "updated_at >= created_at AND (archived_at IS NULL OR archived_at = updated_at)");

                            t.HasCheckConstraint("ck_workflows_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_workflows_name", "length(btrim(name)) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("ck_workflows_revision", "revision >= 0");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowVersionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_versions");

                    b.HasAlternateKey("Id", "WorkflowId", "OwnerUserId")
                        .HasName("ak_workflow_versions_id_workflow_id_owner_user_id");

                    b.HasIndex("WorkflowId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_versions_workflow_id")
                        .HasFilter("status = 1");

                    b.HasIndex("WorkflowId", "OwnerUserId")
                        .HasDatabaseName("ix_workflow_versions_workflow_id_owner_user_id");

                    b.HasIndex("WorkflowId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_versions_workflow_id_version_number");

                    b.ToTable("workflow_versions", "public", t =>
                        {
                            t.HasCheckConstraint("ck_workflow_versions_id", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_workflow_versions_revision", "revision >= 0 AND version_number > 0");

                            t.HasCheckConstraint("ck_workflow_versions_status", "(status = 1 AND published_at IS NULL) OR (status = 2 AND published_at IS NOT NULL AND published_at >= created_at)");
                        });
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.ExecutionLogRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.NodeExecutionRecord", null)
                        .WithMany()
                        .HasForeignKey("NodeExecutionId", "ExecutionId")
                        .HasPrincipalKey("Id", "ExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_execution_logs_node_execution_id_execution_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.InboxMessageRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.OutboxMessageRecord", null)
                        .WithMany()
                        .HasForeignKey("MessageId", "ExecutionId")
                        .HasPrincipalKey("Id", "ExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_inbox_messages_message_id_execution_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.NodeExecutionRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowExecutionRecord", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId", "WorkflowVersionId")
                        .HasPrincipalKey("Id", "WorkflowVersionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_node_executions_execution_id_workflow_version_id");

                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId", "NodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_node_executions_workflow_version_id_node_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.OutboxMessageRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowExecutionRecord", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_messages_execution_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WebhookEndpointRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_endpoints_workflow_id_owner_user_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WebhookIdempotencyRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WebhookEndpointRecord", null)
                        .WithMany()
                        .HasForeignKey("EndpointId", "WorkflowId", "OwnerUserId")
                        .HasPrincipalKey("Id", "WorkflowId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_idempotency_endpoint_id_workflow_id_owner_user_id");

                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowExecutionRecord", null)
                        .WithMany()
                        .HasForeignKey("ExecutionId", "WorkflowId", "OwnerUserId")
                        .HasPrincipalKey("Id", "WorkflowId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_idempotency_execution_id_workflow_id_owner_user_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowConnectionRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId", "SourceNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_connections_workflow_version_id_source_node_id");

                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId", "TargetNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_connections_workflow_version_id_target_node_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowExecutionRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId", "NextNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_workflow_executions_workflow_version_id_next_node_id");

                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WebhookEndpointRecord", null)
                        .WithMany()
                        .HasForeignKey("WebhookEndpointId", "WorkflowId", "OwnerUserId")
                        .HasPrincipalKey("Id", "WorkflowId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_workflow_executions_hook_id_workflow_id_owner_user_id");

                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId", "WorkflowId", "OwnerUserId")
                        .HasPrincipalKey("Id", "WorkflowId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_executions_version_id_workflow_id_owner_user_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowNodeRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowVersionId", "WorkflowId", "OwnerUserId")
                        .HasPrincipalKey("Id", "WorkflowId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_nodes_workflow_version_id_workflow_id_owner_user_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.TechnicalUserRecord", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflows_owner_user_id");

                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowVersionRecord", null)
                        .WithMany()
                        .HasForeignKey("CurrentPublishedVersionId", "Id", "OwnerUserId")
                        .HasPrincipalKey("Id", "WorkflowId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_workflows_current_published_version_id_id_owner_user_id");
                });

            modelBuilder.Entity("FlowForge.Infrastructure.Persistence.Records.WorkflowVersionRecord", b =>
                {
                    b.HasOne("FlowForge.Infrastructure.Persistence.Records.WorkflowRecord", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_versions_workflow_id_owner_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
