<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <ProjectReference Include="../FlowForge.Application/FlowForge.Application.csproj" />
    <ProjectReference Include="../FlowForge.Infrastructure/FlowForge.Infrastructure.csproj" />
  </ItemGroup>
</Project>
